### ISSUE TITLE
Bug with spoken text in the latest no compiled version

### ISSUE THREAD

**Issue by Ali-Bueno** [bradjrenshaw/say-the-spire#11]
I'm not sure how to report this, but in the latest comit, its almost imposible to play. The screen reader quewes the messages of the mod, and it don't reads propperly what you are focusing. For example, if you play some cards, then press the button to exit from the run, the screen reader still read the cards until you manage to spam a lot other options. Then the screen reader starts to read that options if you return to the cards. I hope not sound to confusing.

**Comment by bradjrenshaw** [comment]
I apparently somehow completely missed this issue last year; sorry about that. I'm pretty sure all cases of this have been fixed but let me know if I missed any.
