### ISSUE TITLE
Input buffer setting isn't acknowledged in latest release.

### ISSUE THREAD

**Issue by blindninja97** [bradjrenshaw/say-the-spire#12]
I unfortunately don't know what seems to be happening here, but even if virtual input is set to false in the configuration file, when the game is run it doesn't seem to acknowledge whether or not it's enabled at all.

**Comment by bradjrenshaw** [comment]
Thanks for reporting this; I just found the problem. I deleted a line of code by accident in one of the more recent updates. The result was that it was checking if virtual input was enabled at the end of the update loop but not at the beginning. This lead to the virtual input setting only effecting certain game states with controllers. I will fix this and release a quick patch.
