### ISSUE TITLE
Slay The Spire Russian Localization

### ISSUE THREAD

**Issue by darrthscorrp** [bradjrenshaw/say-the-spire#17]
Here's the russian localization for Slay The Spire, enjoy)
[Slay The Spire russian localization.zip](https://github.com/bradjrenshaw/say-the-spire/files/11056260/Slay.The.Spire.russian.localization.zip)

**Comment by bradjrenshaw** [comment]
Sorry about the delayed response to this one. I just implemented these changes; thanks for taking the time to work on this.
