### ISSUE TITLE
Enhancement request: Fall back on SAPI if a supported screen reader isn't running

### ISSUE THREAD

**Issue by pitermach** [bradjrenshaw/say-the-spire#2]
Currently if you launch the game while you're not using a supported screen reader (EG Narrator, ZDSR) you don't get any speech. It would be good if the mod would switch to using SAPI if a supported screen reader isn't running. 

Tolk already has a trySAPI function built-in for this though it's set to false by default on initialisation, but fixing this shouldn't be too hard.

**Comment by mojsior** [comment]
I agree I am using zdsr and I want to play this game without running nvda. I love this mod

**Comment by bradjrenshaw** [comment]
Oh I thought this was the behavior already. I'll fix this for the next beta.

**Comment by bradjrenshaw** [comment]
This has been fixed for beta 2.
